//
//  FetchBezel for BezelKit
//  Created by Mark Battistella
//

import SwiftUI

@main
struct MainApp: App {
	var body: some Scene {
		WindowGroup {
			Text("Running app")
				.onAppear { logMetrics() }
		}
	}

	/// Logs device-specific metrics such as the model name and screen radius to a text file.
	///
	/// This function gathers device metrics including the device model name and the screen's corner radius,
	/// and saves this information in a JSON-formatted string to a file named `output.txt` in the app's document directory.
	///
	/// If the function encounters any errors during the JSON serialization or file writing operations, it logs those errors to the console and terminates the operation.
	private func logMetrics() {

		// Retrieve the device model name and screen corner radius.
		let deviceModelName = UIDevice.current.modelName
		let deviceRadius = UIScreen.main.radius

		// Create a dictionary to hold the device metrics.
		let metrics: [String: Any] = [
			"identifiers": deviceModelName,
			"bezel": deviceRadius
		]

		// Serialize the metrics dictionary to JSON data.
		let jsonData: Data
		do {
			jsonData = try JSONSerialization.data(withJSONObject: metrics, options: .prettyPrinted)
		} catch {
			print("Failed to create JSON: \(error)")
			return
		}

		// Convert the JSON data to a string.
		let jsonString = String(data: jsonData, encoding: .utf8)!

		// Create the path where the log file will be saved.
		let path = FileManager
			.default
			.urls(for: .documentDirectory, in: .userDomainMask)[0]
			.appendingPathComponent("output.txt")

		// Attempt to write the JSON string to the file at the specified path.
		do {
			try jsonString.write(to: path, atomically: true, encoding: .utf8)
		} catch {
			print("Failed to write logs: \(error)")
		}
	}
}

/// An extension to `UIScreen` for retrieving the corner radius of the device's display.
extension UIScreen {

	/// A private key used to retrieve the display corner radius value via KVC (Key-Value Coding).
	/// This key is generated by reversing and joining the components ["Radius", "Corner", "display", "_"].
	private static let radiusKey: String = {
		let components = ["Radius", "Corner", "display", "_"]
		return components.reversed().joined()
	}()

	/// The radius of the corners of the device's display.
	/// This value is accessed through Key-Value Coding, using a private key.
	///
	/// - Returns: A `CGFloat` value representing the corner radius.
	///   If the corner radius cannot be accessed, this property returns `0`.
	public var radius: CGFloat {
		guard let corner = self.value(forKey: Self.radiusKey) as? CGFloat else {
			return 0
		}
		return corner
	}
}

/// An extension to `UIDevice` for retrieving the model name identifier of the device.
extension UIDevice {

	/// The model name identifier of the device.
	///
	/// For real devices, this identifier is obtained by calling `uname()` function.
	/// For simulators, the identifier is read from the environment variable `SIMULATOR_MODEL_IDENTIFIER`.
	///
	/// - Returns: A `String` representing the model name identifier of the device.
	var modelName: String {

		#if targetEnvironment(simulator)

		// In the case of a simulator, read the identifier from environment variables
		let identifier = ProcessInfo().environment["SIMULATOR_MODEL_IDENTIFIER"]!

		#else

		// In the case of a real device, get the identifier using `uname()`
		var systemInfo = utsname()
		uname(&systemInfo)
		let machineMirror = Mirror(reflecting: systemInfo.machine)
		let identifier = machineMirror.children.reduce("") { identifier, element in
			guard let value = element.value as? Int8, value != 0 else { return identifier }
			return identifier + String(UnicodeScalar(UInt8(value)))
		}

		#endif

		return identifier
	}
}
