# name of the workflow
name: PR checker

# perform this only on these types
on:
  pull_request:

# list the jobs
jobs:

  # job item 1
  job1:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
